//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeValueApp.PrimeValueService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItemRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderItemRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIdField;
        
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrimeValueService.PrimeValueServiceSoap")]
    public interface PrimeValueServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.HelloWorldResponse HelloWorld(PrimeValueApp.PrimeValueService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.HelloWorldResponse> HelloWorldAsync(PrimeValueApp.PrimeValueService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.GetProductsResponse GetProducts(PrimeValueApp.PrimeValueService.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetProductsResponse> GetProductsAsync(PrimeValueApp.PrimeValueService.GetProductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllOrdersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllOrders", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.GetAllOrdersResponse GetAllOrders(PrimeValueApp.PrimeValueService.GetAllOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetAllOrdersResponse> GetAllOrdersAsync(PrimeValueApp.PrimeValueService.GetAllOrdersRequest request);
        
        // CODEGEN: Generating message contract since element name items from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrder", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.CreateOrderResponse CreateOrder(PrimeValueApp.PrimeValueService.CreateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.CreateOrderResponse> CreateOrderAsync(PrimeValueApp.PrimeValueService.CreateOrderRequest request);
        
        // CODEGEN: Generating message contract since element name orderId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderStatus", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.GetOrderStatusResponse GetOrderStatus(PrimeValueApp.PrimeValueService.GetOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetOrderStatusResponse> GetOrderStatusAsync(PrimeValueApp.PrimeValueService.GetOrderStatusRequest request);
        
        // CODEGEN: Generating message contract since element name orderId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessPayment", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.ProcessPaymentResponse ProcessPayment(PrimeValueApp.PrimeValueService.ProcessPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.ProcessPaymentResponse> ProcessPaymentAsync(PrimeValueApp.PrimeValueService.ProcessPaymentRequest request);
        
        // CODEGEN: Generating message contract since element name orderId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentStatus", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.PaymentStatusResponse PaymentStatus(PrimeValueApp.PrimeValueService.PaymentStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.PaymentStatusResponse> PaymentStatusAsync(PrimeValueApp.PrimeValueService.PaymentStatusRequest request);
        
        // CODEGEN: Generating message contract since element name orderId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InitiateShipment", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.InitiateShipmentResponse InitiateShipment(PrimeValueApp.PrimeValueService.InitiateShipmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InitiateShipment", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.InitiateShipmentResponse> InitiateShipmentAsync(PrimeValueApp.PrimeValueService.InitiateShipmentRequest request);
        
        // CODEGEN: Generating message contract since element name orderId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShipmentStatus", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.GetShipmentStatusResponse GetShipmentStatus(PrimeValueApp.PrimeValueService.GetShipmentStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShipmentStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetShipmentStatusResponse> GetShipmentStatusAsync(PrimeValueApp.PrimeValueService.GetShipmentStatusRequest request);
        
        // CODEGEN: Generating message contract since element name orderId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PickPackOrder", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.PickPackOrderResponse PickPackOrder(PrimeValueApp.PrimeValueService.PickPackOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PickPackOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.PickPackOrderResponse> PickPackOrderAsync(PrimeValueApp.PrimeValueService.PickPackOrderRequest request);
        
        // CODEGEN: Generating message contract since element name orderId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DispatchOrder", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.DispatchOrderResponse DispatchOrder(PrimeValueApp.PrimeValueService.DispatchOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DispatchOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.DispatchOrderResponse> DispatchOrderAsync(PrimeValueApp.PrimeValueService.DispatchOrderRequest request);
        
        // CODEGEN: Generating message contract since element name orderId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmDelivery", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.ConfirmDeliveryResponse ConfirmDelivery(PrimeValueApp.PrimeValueService.ConfirmDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.ConfirmDeliveryResponse> ConfirmDeliveryAsync(PrimeValueApp.PrimeValueService.ConfirmDeliveryRequest request);
        
        // CODEGEN: Generating message contract since element name orderId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetShipmentDelivered", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.SetShipmentDeliveredResponse SetShipmentDelivered(PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetShipmentDelivered", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.SetShipmentDeliveredResponse> SetShipmentDeliveredAsync(PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequest request);
        
        // CODEGEN: Generating message contract since element name TestDbConnectionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDbConnection", ReplyAction="*")]
        PrimeValueApp.PrimeValueService.TestDbConnectionResponse TestDbConnection(PrimeValueApp.PrimeValueService.TestDbConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDbConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.TestDbConnectionResponse> TestDbConnectionAsync(PrimeValueApp.PrimeValueService.TestDbConnectionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(PrimeValueApp.PrimeValueService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(PrimeValueApp.PrimeValueService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProducts", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.GetProductsRequestBody Body;
        
        public GetProductsRequest() {
        }
        
        public GetProductsRequest(PrimeValueApp.PrimeValueService.GetProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductsRequestBody {
        
        public GetProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.GetProductsResponseBody Body;
        
        public GetProductsResponse() {
        }
        
        public GetProductsResponse(PrimeValueApp.PrimeValueService.GetProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProductsResult;
        
        public GetProductsResponseBody() {
        }
        
        public GetProductsResponseBody(string GetProductsResult) {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllOrders", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.GetAllOrdersRequestBody Body;
        
        public GetAllOrdersRequest() {
        }
        
        public GetAllOrdersRequest(PrimeValueApp.PrimeValueService.GetAllOrdersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllOrdersRequestBody {
        
        public GetAllOrdersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllOrdersResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.GetAllOrdersResponseBody Body;
        
        public GetAllOrdersResponse() {
        }
        
        public GetAllOrdersResponse(PrimeValueApp.PrimeValueService.GetAllOrdersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllOrdersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllOrdersResult;
        
        public GetAllOrdersResponseBody() {
        }
        
        public GetAllOrdersResponseBody(string GetAllOrdersResult) {
            this.GetAllOrdersResult = GetAllOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrder", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.CreateOrderRequestBody Body;
        
        public CreateOrderRequest() {
        }
        
        public CreateOrderRequest(PrimeValueApp.PrimeValueService.CreateOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PrimeValueApp.PrimeValueService.OrderItemRequest[] items;
        
        public CreateOrderRequestBody() {
        }
        
        public CreateOrderRequestBody(PrimeValueApp.PrimeValueService.OrderItemRequest[] items) {
            this.items = items;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.CreateOrderResponseBody Body;
        
        public CreateOrderResponse() {
        }
        
        public CreateOrderResponse(PrimeValueApp.PrimeValueService.CreateOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateOrderResult;
        
        public CreateOrderResponseBody() {
        }
        
        public CreateOrderResponseBody(string CreateOrderResult) {
            this.CreateOrderResult = CreateOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatus", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.GetOrderStatusRequestBody Body;
        
        public GetOrderStatusRequest() {
        }
        
        public GetOrderStatusRequest(PrimeValueApp.PrimeValueService.GetOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        public GetOrderStatusRequestBody() {
        }
        
        public GetOrderStatusRequestBody(string orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.GetOrderStatusResponseBody Body;
        
        public GetOrderStatusResponse() {
        }
        
        public GetOrderStatusResponse(PrimeValueApp.PrimeValueService.GetOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOrderStatusResult;
        
        public GetOrderStatusResponseBody() {
        }
        
        public GetOrderStatusResponseBody(string GetOrderStatusResult) {
            this.GetOrderStatusResult = GetOrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessPayment", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.ProcessPaymentRequestBody Body;
        
        public ProcessPaymentRequest() {
        }
        
        public ProcessPaymentRequest(PrimeValueApp.PrimeValueService.ProcessPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal amount;
        
        public ProcessPaymentRequestBody() {
        }
        
        public ProcessPaymentRequestBody(string orderId, decimal amount) {
            this.orderId = orderId;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessPaymentResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.ProcessPaymentResponseBody Body;
        
        public ProcessPaymentResponse() {
        }
        
        public ProcessPaymentResponse(PrimeValueApp.PrimeValueService.ProcessPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessPaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessPaymentResult;
        
        public ProcessPaymentResponseBody() {
        }
        
        public ProcessPaymentResponseBody(string ProcessPaymentResult) {
            this.ProcessPaymentResult = ProcessPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentStatus", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.PaymentStatusRequestBody Body;
        
        public PaymentStatusRequest() {
        }
        
        public PaymentStatusRequest(PrimeValueApp.PrimeValueService.PaymentStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        public PaymentStatusRequestBody() {
        }
        
        public PaymentStatusRequestBody(string orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.PaymentStatusResponseBody Body;
        
        public PaymentStatusResponse() {
        }
        
        public PaymentStatusResponse(PrimeValueApp.PrimeValueService.PaymentStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PaymentStatusResult;
        
        public PaymentStatusResponseBody() {
        }
        
        public PaymentStatusResponseBody(string PaymentStatusResult) {
            this.PaymentStatusResult = PaymentStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitiateShipmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitiateShipment", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.InitiateShipmentRequestBody Body;
        
        public InitiateShipmentRequest() {
        }
        
        public InitiateShipmentRequest(PrimeValueApp.PrimeValueService.InitiateShipmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InitiateShipmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string shippingInfoJson;
        
        public InitiateShipmentRequestBody() {
        }
        
        public InitiateShipmentRequestBody(string orderId, string shippingInfoJson) {
            this.orderId = orderId;
            this.shippingInfoJson = shippingInfoJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitiateShipmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitiateShipmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.InitiateShipmentResponseBody Body;
        
        public InitiateShipmentResponse() {
        }
        
        public InitiateShipmentResponse(PrimeValueApp.PrimeValueService.InitiateShipmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InitiateShipmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InitiateShipmentResult;
        
        public InitiateShipmentResponseBody() {
        }
        
        public InitiateShipmentResponseBody(string InitiateShipmentResult) {
            this.InitiateShipmentResult = InitiateShipmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipmentStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShipmentStatus", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.GetShipmentStatusRequestBody Body;
        
        public GetShipmentStatusRequest() {
        }
        
        public GetShipmentStatusRequest(PrimeValueApp.PrimeValueService.GetShipmentStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetShipmentStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        public GetShipmentStatusRequestBody() {
        }
        
        public GetShipmentStatusRequestBody(string orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipmentStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShipmentStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.GetShipmentStatusResponseBody Body;
        
        public GetShipmentStatusResponse() {
        }
        
        public GetShipmentStatusResponse(PrimeValueApp.PrimeValueService.GetShipmentStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetShipmentStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetShipmentStatusResult;
        
        public GetShipmentStatusResponseBody() {
        }
        
        public GetShipmentStatusResponseBody(string GetShipmentStatusResult) {
            this.GetShipmentStatusResult = GetShipmentStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PickPackOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PickPackOrder", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.PickPackOrderRequestBody Body;
        
        public PickPackOrderRequest() {
        }
        
        public PickPackOrderRequest(PrimeValueApp.PrimeValueService.PickPackOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PickPackOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        public PickPackOrderRequestBody() {
        }
        
        public PickPackOrderRequestBody(string orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PickPackOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PickPackOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.PickPackOrderResponseBody Body;
        
        public PickPackOrderResponse() {
        }
        
        public PickPackOrderResponse(PrimeValueApp.PrimeValueService.PickPackOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PickPackOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PickPackOrderResult;
        
        public PickPackOrderResponseBody() {
        }
        
        public PickPackOrderResponseBody(string PickPackOrderResult) {
            this.PickPackOrderResult = PickPackOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DispatchOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DispatchOrder", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.DispatchOrderRequestBody Body;
        
        public DispatchOrderRequest() {
        }
        
        public DispatchOrderRequest(PrimeValueApp.PrimeValueService.DispatchOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DispatchOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string address;
        
        public DispatchOrderRequestBody() {
        }
        
        public DispatchOrderRequestBody(string orderId, string address) {
            this.orderId = orderId;
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DispatchOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DispatchOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.DispatchOrderResponseBody Body;
        
        public DispatchOrderResponse() {
        }
        
        public DispatchOrderResponse(PrimeValueApp.PrimeValueService.DispatchOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DispatchOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DispatchOrderResult;
        
        public DispatchOrderResponseBody() {
        }
        
        public DispatchOrderResponseBody(string DispatchOrderResult) {
            this.DispatchOrderResult = DispatchOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmDeliveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmDelivery", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.ConfirmDeliveryRequestBody Body;
        
        public ConfirmDeliveryRequest() {
        }
        
        public ConfirmDeliveryRequest(PrimeValueApp.PrimeValueService.ConfirmDeliveryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmDeliveryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        public ConfirmDeliveryRequestBody() {
        }
        
        public ConfirmDeliveryRequestBody(string orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmDeliveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmDeliveryResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.ConfirmDeliveryResponseBody Body;
        
        public ConfirmDeliveryResponse() {
        }
        
        public ConfirmDeliveryResponse(PrimeValueApp.PrimeValueService.ConfirmDeliveryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmDeliveryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConfirmDeliveryResult;
        
        public ConfirmDeliveryResponseBody() {
        }
        
        public ConfirmDeliveryResponseBody(string ConfirmDeliveryResult) {
            this.ConfirmDeliveryResult = ConfirmDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetShipmentDeliveredRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetShipmentDelivered", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequestBody Body;
        
        public SetShipmentDeliveredRequest() {
        }
        
        public SetShipmentDeliveredRequest(PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetShipmentDeliveredRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        public SetShipmentDeliveredRequestBody() {
        }
        
        public SetShipmentDeliveredRequestBody(string orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetShipmentDeliveredResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetShipmentDeliveredResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.SetShipmentDeliveredResponseBody Body;
        
        public SetShipmentDeliveredResponse() {
        }
        
        public SetShipmentDeliveredResponse(PrimeValueApp.PrimeValueService.SetShipmentDeliveredResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetShipmentDeliveredResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetShipmentDeliveredResult;
        
        public SetShipmentDeliveredResponseBody() {
        }
        
        public SetShipmentDeliveredResponseBody(string SetShipmentDeliveredResult) {
            this.SetShipmentDeliveredResult = SetShipmentDeliveredResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDbConnectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDbConnection", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.TestDbConnectionRequestBody Body;
        
        public TestDbConnectionRequest() {
        }
        
        public TestDbConnectionRequest(PrimeValueApp.PrimeValueService.TestDbConnectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestDbConnectionRequestBody {
        
        public TestDbConnectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDbConnectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDbConnectionResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrimeValueApp.PrimeValueService.TestDbConnectionResponseBody Body;
        
        public TestDbConnectionResponse() {
        }
        
        public TestDbConnectionResponse(PrimeValueApp.PrimeValueService.TestDbConnectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDbConnectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestDbConnectionResult;
        
        public TestDbConnectionResponseBody() {
        }
        
        public TestDbConnectionResponseBody(string TestDbConnectionResult) {
            this.TestDbConnectionResult = TestDbConnectionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrimeValueServiceSoapChannel : PrimeValueApp.PrimeValueService.PrimeValueServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrimeValueServiceSoapClient : System.ServiceModel.ClientBase<PrimeValueApp.PrimeValueService.PrimeValueServiceSoap>, PrimeValueApp.PrimeValueService.PrimeValueServiceSoap {
        
        public PrimeValueServiceSoapClient() {
        }
        
        public PrimeValueServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrimeValueServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimeValueServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimeValueServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.HelloWorldResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.HelloWorld(PrimeValueApp.PrimeValueService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            PrimeValueApp.PrimeValueService.HelloWorldRequest inValue = new PrimeValueApp.PrimeValueService.HelloWorldRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.HelloWorldRequestBody();
            PrimeValueApp.PrimeValueService.HelloWorldResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.HelloWorldResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.HelloWorldAsync(PrimeValueApp.PrimeValueService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.HelloWorldResponse> HelloWorldAsync() {
            PrimeValueApp.PrimeValueService.HelloWorldRequest inValue = new PrimeValueApp.PrimeValueService.HelloWorldRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.HelloWorldRequestBody();
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.GetProductsResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.GetProducts(PrimeValueApp.PrimeValueService.GetProductsRequest request) {
            return base.Channel.GetProducts(request);
        }
        
        public string GetProducts() {
            PrimeValueApp.PrimeValueService.GetProductsRequest inValue = new PrimeValueApp.PrimeValueService.GetProductsRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.GetProductsRequestBody();
            PrimeValueApp.PrimeValueService.GetProductsResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).GetProducts(inValue);
            return retVal.Body.GetProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetProductsResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.GetProductsAsync(PrimeValueApp.PrimeValueService.GetProductsRequest request) {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetProductsResponse> GetProductsAsync() {
            PrimeValueApp.PrimeValueService.GetProductsRequest inValue = new PrimeValueApp.PrimeValueService.GetProductsRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.GetProductsRequestBody();
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).GetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.GetAllOrdersResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.GetAllOrders(PrimeValueApp.PrimeValueService.GetAllOrdersRequest request) {
            return base.Channel.GetAllOrders(request);
        }
        
        public string GetAllOrders() {
            PrimeValueApp.PrimeValueService.GetAllOrdersRequest inValue = new PrimeValueApp.PrimeValueService.GetAllOrdersRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.GetAllOrdersRequestBody();
            PrimeValueApp.PrimeValueService.GetAllOrdersResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).GetAllOrders(inValue);
            return retVal.Body.GetAllOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetAllOrdersResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.GetAllOrdersAsync(PrimeValueApp.PrimeValueService.GetAllOrdersRequest request) {
            return base.Channel.GetAllOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetAllOrdersResponse> GetAllOrdersAsync() {
            PrimeValueApp.PrimeValueService.GetAllOrdersRequest inValue = new PrimeValueApp.PrimeValueService.GetAllOrdersRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.GetAllOrdersRequestBody();
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).GetAllOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.CreateOrderResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.CreateOrder(PrimeValueApp.PrimeValueService.CreateOrderRequest request) {
            return base.Channel.CreateOrder(request);
        }
        
        public string CreateOrder(PrimeValueApp.PrimeValueService.OrderItemRequest[] items) {
            PrimeValueApp.PrimeValueService.CreateOrderRequest inValue = new PrimeValueApp.PrimeValueService.CreateOrderRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.CreateOrderRequestBody();
            inValue.Body.items = items;
            PrimeValueApp.PrimeValueService.CreateOrderResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).CreateOrder(inValue);
            return retVal.Body.CreateOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.CreateOrderResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.CreateOrderAsync(PrimeValueApp.PrimeValueService.CreateOrderRequest request) {
            return base.Channel.CreateOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.CreateOrderResponse> CreateOrderAsync(PrimeValueApp.PrimeValueService.OrderItemRequest[] items) {
            PrimeValueApp.PrimeValueService.CreateOrderRequest inValue = new PrimeValueApp.PrimeValueService.CreateOrderRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.CreateOrderRequestBody();
            inValue.Body.items = items;
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).CreateOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.GetOrderStatusResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.GetOrderStatus(PrimeValueApp.PrimeValueService.GetOrderStatusRequest request) {
            return base.Channel.GetOrderStatus(request);
        }
        
        public string GetOrderStatus(string orderId) {
            PrimeValueApp.PrimeValueService.GetOrderStatusRequest inValue = new PrimeValueApp.PrimeValueService.GetOrderStatusRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.GetOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            PrimeValueApp.PrimeValueService.GetOrderStatusResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).GetOrderStatus(inValue);
            return retVal.Body.GetOrderStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetOrderStatusResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.GetOrderStatusAsync(PrimeValueApp.PrimeValueService.GetOrderStatusRequest request) {
            return base.Channel.GetOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetOrderStatusResponse> GetOrderStatusAsync(string orderId) {
            PrimeValueApp.PrimeValueService.GetOrderStatusRequest inValue = new PrimeValueApp.PrimeValueService.GetOrderStatusRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.GetOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).GetOrderStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.ProcessPaymentResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.ProcessPayment(PrimeValueApp.PrimeValueService.ProcessPaymentRequest request) {
            return base.Channel.ProcessPayment(request);
        }
        
        public string ProcessPayment(string orderId, decimal amount) {
            PrimeValueApp.PrimeValueService.ProcessPaymentRequest inValue = new PrimeValueApp.PrimeValueService.ProcessPaymentRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.ProcessPaymentRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            PrimeValueApp.PrimeValueService.ProcessPaymentResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).ProcessPayment(inValue);
            return retVal.Body.ProcessPaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.ProcessPaymentResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.ProcessPaymentAsync(PrimeValueApp.PrimeValueService.ProcessPaymentRequest request) {
            return base.Channel.ProcessPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.ProcessPaymentResponse> ProcessPaymentAsync(string orderId, decimal amount) {
            PrimeValueApp.PrimeValueService.ProcessPaymentRequest inValue = new PrimeValueApp.PrimeValueService.ProcessPaymentRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.ProcessPaymentRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).ProcessPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.PaymentStatusResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.PaymentStatus(PrimeValueApp.PrimeValueService.PaymentStatusRequest request) {
            return base.Channel.PaymentStatus(request);
        }
        
        public string PaymentStatus(string orderId) {
            PrimeValueApp.PrimeValueService.PaymentStatusRequest inValue = new PrimeValueApp.PrimeValueService.PaymentStatusRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.PaymentStatusRequestBody();
            inValue.Body.orderId = orderId;
            PrimeValueApp.PrimeValueService.PaymentStatusResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).PaymentStatus(inValue);
            return retVal.Body.PaymentStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.PaymentStatusResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.PaymentStatusAsync(PrimeValueApp.PrimeValueService.PaymentStatusRequest request) {
            return base.Channel.PaymentStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.PaymentStatusResponse> PaymentStatusAsync(string orderId) {
            PrimeValueApp.PrimeValueService.PaymentStatusRequest inValue = new PrimeValueApp.PrimeValueService.PaymentStatusRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.PaymentStatusRequestBody();
            inValue.Body.orderId = orderId;
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).PaymentStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.InitiateShipmentResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.InitiateShipment(PrimeValueApp.PrimeValueService.InitiateShipmentRequest request) {
            return base.Channel.InitiateShipment(request);
        }
        
        public string InitiateShipment(string orderId, string shippingInfoJson) {
            PrimeValueApp.PrimeValueService.InitiateShipmentRequest inValue = new PrimeValueApp.PrimeValueService.InitiateShipmentRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.InitiateShipmentRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.shippingInfoJson = shippingInfoJson;
            PrimeValueApp.PrimeValueService.InitiateShipmentResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).InitiateShipment(inValue);
            return retVal.Body.InitiateShipmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.InitiateShipmentResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.InitiateShipmentAsync(PrimeValueApp.PrimeValueService.InitiateShipmentRequest request) {
            return base.Channel.InitiateShipmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.InitiateShipmentResponse> InitiateShipmentAsync(string orderId, string shippingInfoJson) {
            PrimeValueApp.PrimeValueService.InitiateShipmentRequest inValue = new PrimeValueApp.PrimeValueService.InitiateShipmentRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.InitiateShipmentRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.shippingInfoJson = shippingInfoJson;
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).InitiateShipmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.GetShipmentStatusResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.GetShipmentStatus(PrimeValueApp.PrimeValueService.GetShipmentStatusRequest request) {
            return base.Channel.GetShipmentStatus(request);
        }
        
        public string GetShipmentStatus(string orderId) {
            PrimeValueApp.PrimeValueService.GetShipmentStatusRequest inValue = new PrimeValueApp.PrimeValueService.GetShipmentStatusRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.GetShipmentStatusRequestBody();
            inValue.Body.orderId = orderId;
            PrimeValueApp.PrimeValueService.GetShipmentStatusResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).GetShipmentStatus(inValue);
            return retVal.Body.GetShipmentStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetShipmentStatusResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.GetShipmentStatusAsync(PrimeValueApp.PrimeValueService.GetShipmentStatusRequest request) {
            return base.Channel.GetShipmentStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.GetShipmentStatusResponse> GetShipmentStatusAsync(string orderId) {
            PrimeValueApp.PrimeValueService.GetShipmentStatusRequest inValue = new PrimeValueApp.PrimeValueService.GetShipmentStatusRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.GetShipmentStatusRequestBody();
            inValue.Body.orderId = orderId;
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).GetShipmentStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.PickPackOrderResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.PickPackOrder(PrimeValueApp.PrimeValueService.PickPackOrderRequest request) {
            return base.Channel.PickPackOrder(request);
        }
        
        public string PickPackOrder(string orderId) {
            PrimeValueApp.PrimeValueService.PickPackOrderRequest inValue = new PrimeValueApp.PrimeValueService.PickPackOrderRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.PickPackOrderRequestBody();
            inValue.Body.orderId = orderId;
            PrimeValueApp.PrimeValueService.PickPackOrderResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).PickPackOrder(inValue);
            return retVal.Body.PickPackOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.PickPackOrderResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.PickPackOrderAsync(PrimeValueApp.PrimeValueService.PickPackOrderRequest request) {
            return base.Channel.PickPackOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.PickPackOrderResponse> PickPackOrderAsync(string orderId) {
            PrimeValueApp.PrimeValueService.PickPackOrderRequest inValue = new PrimeValueApp.PrimeValueService.PickPackOrderRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.PickPackOrderRequestBody();
            inValue.Body.orderId = orderId;
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).PickPackOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.DispatchOrderResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.DispatchOrder(PrimeValueApp.PrimeValueService.DispatchOrderRequest request) {
            return base.Channel.DispatchOrder(request);
        }
        
        public string DispatchOrder(string orderId, string address) {
            PrimeValueApp.PrimeValueService.DispatchOrderRequest inValue = new PrimeValueApp.PrimeValueService.DispatchOrderRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.DispatchOrderRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.address = address;
            PrimeValueApp.PrimeValueService.DispatchOrderResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).DispatchOrder(inValue);
            return retVal.Body.DispatchOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.DispatchOrderResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.DispatchOrderAsync(PrimeValueApp.PrimeValueService.DispatchOrderRequest request) {
            return base.Channel.DispatchOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.DispatchOrderResponse> DispatchOrderAsync(string orderId, string address) {
            PrimeValueApp.PrimeValueService.DispatchOrderRequest inValue = new PrimeValueApp.PrimeValueService.DispatchOrderRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.DispatchOrderRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.address = address;
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).DispatchOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.ConfirmDeliveryResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.ConfirmDelivery(PrimeValueApp.PrimeValueService.ConfirmDeliveryRequest request) {
            return base.Channel.ConfirmDelivery(request);
        }
        
        public string ConfirmDelivery(string orderId) {
            PrimeValueApp.PrimeValueService.ConfirmDeliveryRequest inValue = new PrimeValueApp.PrimeValueService.ConfirmDeliveryRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.ConfirmDeliveryRequestBody();
            inValue.Body.orderId = orderId;
            PrimeValueApp.PrimeValueService.ConfirmDeliveryResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).ConfirmDelivery(inValue);
            return retVal.Body.ConfirmDeliveryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.ConfirmDeliveryResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.ConfirmDeliveryAsync(PrimeValueApp.PrimeValueService.ConfirmDeliveryRequest request) {
            return base.Channel.ConfirmDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.ConfirmDeliveryResponse> ConfirmDeliveryAsync(string orderId) {
            PrimeValueApp.PrimeValueService.ConfirmDeliveryRequest inValue = new PrimeValueApp.PrimeValueService.ConfirmDeliveryRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.ConfirmDeliveryRequestBody();
            inValue.Body.orderId = orderId;
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).ConfirmDeliveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.SetShipmentDeliveredResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.SetShipmentDelivered(PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequest request) {
            return base.Channel.SetShipmentDelivered(request);
        }
        
        public string SetShipmentDelivered(string orderId) {
            PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequest inValue = new PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequestBody();
            inValue.Body.orderId = orderId;
            PrimeValueApp.PrimeValueService.SetShipmentDeliveredResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).SetShipmentDelivered(inValue);
            return retVal.Body.SetShipmentDeliveredResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.SetShipmentDeliveredResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.SetShipmentDeliveredAsync(PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequest request) {
            return base.Channel.SetShipmentDeliveredAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.SetShipmentDeliveredResponse> SetShipmentDeliveredAsync(string orderId) {
            PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequest inValue = new PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.SetShipmentDeliveredRequestBody();
            inValue.Body.orderId = orderId;
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).SetShipmentDeliveredAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrimeValueApp.PrimeValueService.TestDbConnectionResponse PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.TestDbConnection(PrimeValueApp.PrimeValueService.TestDbConnectionRequest request) {
            return base.Channel.TestDbConnection(request);
        }
        
        public string TestDbConnection() {
            PrimeValueApp.PrimeValueService.TestDbConnectionRequest inValue = new PrimeValueApp.PrimeValueService.TestDbConnectionRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.TestDbConnectionRequestBody();
            PrimeValueApp.PrimeValueService.TestDbConnectionResponse retVal = ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).TestDbConnection(inValue);
            return retVal.Body.TestDbConnectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.TestDbConnectionResponse> PrimeValueApp.PrimeValueService.PrimeValueServiceSoap.TestDbConnectionAsync(PrimeValueApp.PrimeValueService.TestDbConnectionRequest request) {
            return base.Channel.TestDbConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrimeValueApp.PrimeValueService.TestDbConnectionResponse> TestDbConnectionAsync() {
            PrimeValueApp.PrimeValueService.TestDbConnectionRequest inValue = new PrimeValueApp.PrimeValueService.TestDbConnectionRequest();
            inValue.Body = new PrimeValueApp.PrimeValueService.TestDbConnectionRequestBody();
            return ((PrimeValueApp.PrimeValueService.PrimeValueServiceSoap)(this)).TestDbConnectionAsync(inValue);
        }
    }
}
